"""
Portfolio Ledger

Responsibilities
----------------
Maintain the financial accounting state of the trading account.

Owns:
    • Opening Capital
    • Available Capital
    • Blocked Capital
    • Gross PnL
    • Net PnL
    • Closed Trades
    • Financial Charges

Does NOT:
    • Place orders
    • Manage positions
    • Calculate signals
    • Know broker APIs
    • Know Telegram
    • Know Strategy

All financial calculations must remain inside this module.
"""

from datetime import datetime


class PortfolioLedger:
    """
    Financial accounting ledger.

    This module records financial events generated by the Engine
    and maintains the current financial state of the portfolio.
    """

    def __init__(self):
        self.reset()

    # --------------------------------------------------
    # Lifecycle
    # --------------------------------------------------

    def reset(self):
        self._transaction_id = 0

        self._opening_capital = 0.0
        self._available_capital = 0.0
        self._blocked_capital = 0.0

        self._gross_pnl = 0.0
        self._net_pnl = 0.0

        self._opened_trades = 0
        self._closed_trades = 0

        # Charges (Phase 2)
        self._brokerage = 0.0
        self._exchange_charges = 0.0
        self._gst = 0.0
        self._stt = 0.0
        self._sebi_charges = 0.0
        self._stamp_duty = 0.0

        # Event Journal
        self._events = []

    # --------------------------------------------------
    # Trading Day
    # --------------------------------------------------

    def start_day(self, opening_capital: float):
        self.reset()

        self._opening_capital = float(opening_capital)
        self._available_capital = float(opening_capital)

    # --------------------------------------------------
    # Financial Events
    # --------------------------------------------------

    def record_buy(self, capital_used: float):
        capital_used = float(capital_used)

        self._transaction_id += 1

        self._blocked_capital += capital_used
        self._available_capital -= capital_used
        
        self._opened_trades += 1

        self._events.append({
            "transaction_id": self._transaction_id,
            "timestamp": datetime.now(),
            "event": "BUY",

            "capital_used": capital_used,
            "capital_before": self._available_capital + capital_used,
            "capital_after": self._available_capital,

            "available_capital": self._available_capital,
            "blocked_capital": self._blocked_capital,

            "gross_pnl": self._gross_pnl,
            "net_pnl": self._net_pnl,
        })

    def record_sell(
        self,
        capital_released: float,
        gross_pnl: float
    ):
        capital_released = float(capital_released)
        gross_pnl = float(gross_pnl)

        self._transaction_id += 1

        blocked_release = capital_released - gross_pnl

        self._blocked_capital -= blocked_release
        self._available_capital += capital_released

        self._gross_pnl += gross_pnl

        # Charges are zero in Phase 1
        total_charges = (
            self._brokerage
            + self._exchange_charges
            + self._gst
            + self._stt
            + self._sebi_charges
            + self._stamp_duty
        )

        self._net_pnl = self._gross_pnl - total_charges

        self._closed_trades += 1

        self._events.append({
            "transaction_id": self._transaction_id,
            "timestamp": datetime.now(),
            "event": "SELL",

            "capital_released": capital_released,
            "capital_before": self._available_capital - capital_released,
            "capital_after": self._available_capital,
            "gross_pnl": gross_pnl,

            "available_capital": self._available_capital,
            "blocked_capital": self._blocked_capital,

            "net_pnl": self._net_pnl,
        })

    # --------------------------------------------------
    # Read-only Accessors
    # --------------------------------------------------

    def transaction_id(self):
        return self._transaction_id

    def opening_capital(self):
        return self._opening_capital

    def available_capital(self):
        return self._available_capital

    def blocked_capital(self):
        return self._blocked_capital

    def gross_pnl(self):
        return self._gross_pnl

    def net_pnl(self):
        return self._net_pnl

    def opened_trades(self):
        return self._opened_trades

    def closed_trades(self):
        return self._closed_trades

    def open_trades(self):
        return self._opened_trades - self._closed_trades

    def closing_capital(self):
        return self._opening_capital + self._net_pnl

    def events(self):
        return list(self._events)

    # --------------------------------------------------
    # Charges
    # --------------------------------------------------

    def brokerage(self):
        return self._brokerage

    def exchange_charges(self):
        return self._exchange_charges

    def gst(self):
        return self._gst

    def stt(self):
        return self._stt

    def sebi_charges(self):
        return self._sebi_charges

    def stamp_duty(self):
        return self._stamp_duty

    # --------------------------------------------------
    # Summary
    # --------------------------------------------------

    def summary(self):
        return {
            "transaction_id": self._transaction_id,

            "opening_capital": self._opening_capital,
            "available_capital": self._available_capital,
            "blocked_capital": self._blocked_capital,

            "gross_pnl": self._gross_pnl,
            "net_pnl": self._net_pnl,

            "opened_trades": self._opened_trades,
            "closed_trades": self._closed_trades,
            "open_trades": self.open_trades(),

            "brokerage": self._brokerage,
            "exchange_charges": self._exchange_charges,
            "gst": self._gst,
            "stt": self._stt,
            "sebi_charges": self._sebi_charges,
            "stamp_duty": self._stamp_duty,

            "closing_capital": self.closing_capital(),
        }